version: '3.0'

services:
  grafana:
    container_name: 'grafanaplugin-s3-datasource'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-latest}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./provisioning:/etc/grafana/provisioning
      - ./dist:/var/lib/grafana/plugins/grafanaplugin-s3-datasource
